### PR TITLE
No location cpt hide map

### PR DESCRIPTION
**Pull request by viruthagiri**

### CODE REVIEW

**Comment by Stiofan** [comment]
have u tested this? this does not seem to be the best solution.

Stiofan

**Comment by viruthagiri** [comment]
Yes stiofan. When right or left sidebar enabled in listing page settings, this actually displays the normal sidebar.

I tried to display normal DS page. But that requires heavy css changes too since SD css modifies listings page layout.

The code I added is simple. but does the job. 

If you want me to do it in different let me know. 

I'll add custom body class and override the SD styles for non map post types.

**Comment by Stiofan** [comment]
the right hand side is still fixed, maybe it might be best to remove the right section and just make it full width?

**Comment by viruthagiri** [comment]
If we make it full width, then we have to override the supreme css for that too. I'm sure at some point a user will ask for sidebar. In that case we have to override the css again.

So i guess, it would be much better to have sidebar by default and then give custom styles if user needs full width.

**Comment by viruthagiri** [comment]
Let me try to improve the listing page design for non location post types.

**Comment by Stiofan** [comment]
can u setup a demo somewhere so i can test it before u add this pull

**Pull request merged**
